timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
      - BASE_REF=$_PULL_BASE_REF
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
      # default cloudbuild has HOME=/builder/home and docker buildx is in /root/.docker/cli-plugins/docker-buildx
      # set the home to /root explicitly to if using docker buildx
      - HOME=/root
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && cd images/fastcgi-helloserver && make push
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
