{{- if and .Values.controller.wallarm.enabled (not .Values.controller.wallarm.existingSecret.enabled) -}}
apiVersion: v1
data:
  token: {{ .Values.controller.wallarm.token | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "ingress-nginx.wallarmSecret" . }}
type: Opaque
{{- end }}
