apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.controller.configAnnotations }}
  annotations: {{ toYaml .Values.controller.configAnnotations | nindent 4 }}
{{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}
  namespace: {{ include "ingress-nginx.namespace" . }}
data:
  allow-snippet-annotations: "{{ .Values.controller.allowSnippetAnnotations }}"
{{- if .Values.controller.wallarm.enabled }}
  enable-wallarm: "{{ .Values.controller.wallarm.enabled }}"
  wallarm-upstream-service: "{{ include "ingress-nginx.controller.fullname" . }}-wallarm-tarantool"
  wallarm-metrics-port: "{{ .Values.controller.wallarm.metrics.port }}"
  wallarm-apifw-enabled: "{{ .Values.controller.wallarm.apiFirewall.enabled }}"
  wallarm-apifw-port: "{{ .Values.controller.wallarm.apiFirewall.config.mainPort }}"
{{- if .Values.controller.wallarm.fallback }}
  wallarm-fallback: "{{ .Values.controller.wallarm.fallback }}"
{{- end }}
{{- end }}
{{- if .Values.controller.addHeaders }}
  add-headers: {{ include "ingress-nginx.namespace" . }}/{{ include "ingress-nginx.fullname" . }}-custom-add-headers
{{- end }}
{{- if .Values.controller.proxySetHeaders }}
  proxy-set-headers: {{ include "ingress-nginx.namespace" . }}/{{ include "ingress-nginx.fullname" . }}-custom-proxy-headers
{{- end }}
{{- if .Values.dhParam }}
  ssl-dh-param: {{ include "ingress-nginx.namespace" . }}/{{ include "ingress-nginx.controller.fullname" . }}
{{- end }}
{{- range $key, $value := .Values.controller.config }}
  {{- $key | nindent 2 }}: {{ tpl (toString $value) $ | quote }}
{{- end }}
