{{- if and (.Values.validation.enableCel) (semverCompare ">=1.30-0" .Capabilities.KubeVersion.Version) }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-safety-net-binding
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  policyName: ingress-safety-net
  validationActions: ["Deny"]
  matchResources:
    namespaceSelector: {}  
{{- end }}