{{- if .Values.controller.wallarm.enabled }}
{{- if eq .Values.controller.wallarm.postanalytics.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmPostanalyticsName" . }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}-wallarm-wstore
  namespace: {{ include "ingress-nginx.namespace" . }}
  {{- if .Values.controller.wallarm.postanalytics.annotations }}
  annotations:
  {{ toYaml .Values.controller.wallarm.postanalytics.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ingress-nginx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "ingress-nginx.wallarmPostanalyticsName" . }}
  replicas: {{ .Values.controller.wallarm.postanalytics.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        checksum/wcli: {{ .Values.controller.wallarm.wcli | toJson | sha256sum }}
      {{- if not .Values.controller.wallarm.existingSecret.enabled }}
        checksum/token: {{ .Values.controller.wallarm.token | sha256sum }}
      {{- end }}
      {{- with .Values.controller.wallarm.postanalytics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingress-nginx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "ingress-nginx.wallarmPostanalyticsName" . }}
      {{- with .Values.controller.wallarm.postanalytics.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.controller.wallarm.postanalytics.terminationGracePeriodSeconds }}
      initContainers:
        {{ $_ := set .Values "register_mode" "post_analytic" }}
        {{ include "ingress-nginx.wallarmInitContainer.init" . | nindent 8 }}
      containers:
        {{ include "ingress-nginx.wallarmWcliContainer" . | nindent 8 }}
        - name: wstore
        {{- if .Values.controller.wallarm.postanalytics.image }}
          {{- with .Values.controller.wallarm.postanalytics.image }}
          image: "{{ .repository }}:{{ .tag }}"
          {{- end }}
        {{- else }}
          image: "{{ .Values.controller.wallarm.helpers.image }}:{{ .Values.controller.wallarm.helpers.tag }}"
        {{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          args: ["wstore"]
          env:
            - name: SLAB_ALLOC_ARENA
              value: "{{ .Values.controller.wallarm.postanalytics.arena }}"
          {{- if (index .Values "controller" "wallarm" "postanalytics" "extraEnvs") }}
            {{- toYaml (index .Values "controller" "wallarm" "postanalytics" "extraEnvs") | nindent 12 }}
          {{- end }}
          securityContext: {{ include "ingress-nginx.controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/wallarm/etc/wallarm
            name: wallarm
          livenessProbe:
            tcpSocket:
              port: {{ template "ingress-nginx.wallarmPostanalyticsPort" . }}
            initialDelaySeconds: {{ .Values.controller.wallarm.postanalytics.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controller.wallarm.postanalytics.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controller.wallarm.postanalytics.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.controller.wallarm.postanalytics.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.controller.wallarm.postanalytics.livenessProbe.failureThreshold }}
          ports:
            - name: wstore
              containerPort: {{ template "ingress-nginx.wallarmPostanalyticsPort" . }}
              protocol: TCP
        {{- if .Values.controller.wallarm.postanalytics.resources }}
          resources: {{ toYaml .Values.controller.wallarm.postanalytics.resources | nindent 12 }}
        {{- end }}
        - name: wallarm-appstructure
        {{- if (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
          {{- with (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
          image: "{{ .repository }}:{{ .tag }}"
          {{- end }}
        {{- else }}
          image: "{{ .Values.controller.wallarm.helpers.image }}:{{ .Values.controller.wallarm.helpers.tag }}"
        {{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          args: ["appstructure"]
        {{- if (index .Values "controller" "wallarm" "wallarm-appstructure" "extraEnvs") }}
          env:
            {{- toYaml (index .Values "controller" "wallarm" "wallarm-appstructure" "extraEnvs") | nindent 12 }}
        {{- end }}
          securityContext: {{ include "ingress-nginx.controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/wallarm/etc/wallarm
            name: wallarm
        {{- if index .Values "controller" "wallarm" "wallarm-appstructure" "resources" }}
          resources: {{ toYaml (index .Values "controller" "wallarm" "wallarm-appstructure" "resources") | nindent 12 }}
        {{- end }}
    {{- if .Values.controller.wallarm.postanalytics.nodeSelector }}
      nodeSelector: {{ toYaml .Values.controller.wallarm.postanalytics.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.postanalytics.tolerations }}
      tolerations: {{ toYaml .Values.controller.wallarm.postanalytics.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.postanalytics.affinity }}
      affinity: {{ toYaml .Values.controller.wallarm.postanalytics.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.postanalytics.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.controller.wallarm.postanalytics.topologySpreadConstraints | nindent 8 }}
    {{- end }}
      volumes:
        - name: wallarm
          emptyDir: {}
        - name: wallarm-acl
          emptyDir: {}
        - name: wallarm-apifw
          emptyDir: {}
        {{- include "ingress-nginx.wallarmTokenVolume" . | nindent 8 }}
{{- end }}
{{- end }}
