apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "ingress-nginx.wallarmTarantoolCronConfig" . }}
  namespace: {{ .Release.Namespace }}
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    loglevel={{ .Values.controller.wallarm.cron.logLevel }}
    logfile=/dev/stdout
    logfile_maxbytes=0
    pidfile=/opt/wallarm/run/supervisor/pid
    {{- with .Values.controller.wallarm.cron.commands.exportAttacks }}
    # export-attacks
    [program:export-attacks]
    command=/opt/wallarm/usr/share/wallarm-common/export-attacks -r -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.exportCounters }}
    # export-counters
    [program:export-counters]
    command=/opt/wallarm/usr/share/wallarm-common/export-counters -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.exportEnvironment }}
    # export-environment
    [program:export-environment]
    command=/opt/wallarm/usr/share/wallarm-common/export-environment -w -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.bruteDetect }}
    # brute-detect
    [program:brute-detect]
    command=/opt/wallarm/usr/share/wallarm-common/brute-detect -w -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.syncMarkers }}
    # sync-markers
    [program:sync-markers]
    command=/opt/wallarm/usr/share/wallarm-common/sync-markers -w -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.weakJwtDetect }}
    # weak-jwt-detect
    [program:weak-jwt-detect]
    command=/opt/wallarm/usr/share/wallarm-common/weak-jwt-detect -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.syncNode }}
    # sync-node
    [program:sync-node]
    command=/opt/wallarm/usr/share/wallarm-common/syncnode -f -p -r 120 -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.exportBlockedStat }}
    # export-blocked-stats
    [program:export-blocked-stats]
    command=/opt/wallarm/usr/share/wallarm-common/export-blocked-stats -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}

    {{- with .Values.controller.wallarm.cron.commands.detectCredStuffing }}
    # detect-cred-stuffing
    [program:detect-cred-stuffing]
    command=/opt/wallarm/usr/share/wallarm-common/detect-cred-stuffing -l STDOUT -L {{ .logLevel }}
    autorestart=true
    startretries=4294967295
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    {{- end }}
