{{- if .Values.controller.wallarm.enabled }}
{{- if eq .Values.controller.wallarm.tarantool.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}-wallarm-tarantool
  namespace: {{ .Release.Namespace }}
  {{- if .Values.controller.wallarm.tarantool.annotations }}
  annotations: {{ toYaml .Values.controller.wallarm.tarantool.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ingress-nginx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "ingress-nginx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    spec:
      {{- if .Values.controller.wallarm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.controller.wallarm.imagePullSecrets | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.controller.wallarm.tarantool.terminationGracePeriodSeconds }}
      initContainers:
{{ include "ingress-nginx.wallarmInitContainer.addNode" . | indent 8 }}
      containers:
{{ include "ingress-nginx.wallarmCronContainer" . | indent 8 }}
        - name: tarantool
{{- if .Values.controller.wallarm.tarantool.image }}
  {{- with .Values.controller.wallarm.tarantool.image }}
          image: "{{ .repository }}:{{ .tag }}"
  {{- end }}
{{- else }}
          image: "wallarm/ingress-tarantool:{{ .Values.controller.image.tag }}"
{{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          env:
            - name: SLAB_ALLOC_ARENA
              value: "{{ .Values.controller.wallarm.tarantool.arena }}"
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ template "ingress-nginx.wallarmTarantoolPort" . }}
            initialDelaySeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.controller.wallarm.tarantool.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.controller.wallarm.tarantool.livenessProbe.failureThreshold }}
          ports:
            - name: tarantool
              containerPort: {{ template "ingress-nginx.wallarmTarantoolPort" . }}
              protocol: TCP
          resources:
{{ toYaml .Values.controller.wallarm.tarantool.resources | indent 12 }}
        - name: heartbeat
{{- if .Values.controller.wallarm.heartbeat.image }}
  {{- with .Values.controller.wallarm.heartbeat.image }}
          image: "{{ .repository }}:{{ .tag }}"
  {{- end }}
{{- else }}
          image: "wallarm/ingress-ruby:{{ .Values.controller.image.tag }}"
{{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          command: ["/bin/dumb-init", "--"]
          args: ["/opt/wallarm/ruby/usr/share/wallarm-common/syncnode", "-p", "-r", "120", "-l", "STDOUT", "-L", "DEBUG"]
          env:
          {{- include "wallarm.credentials" . | nindent 10 }}
          - name: WALLARM_SYNCNODE
            value: "no"
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/wallarm
            name: wallarm
          resources:
{{ toYaml .Values.controller.wallarm.heartbeat.resources | indent 12 }}
        - name: wallarm-appstructure
{{- if (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
  {{- with (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
          image: "{{ .repository }}:{{ .tag }}"
  {{- end }}
{{- else }}
          image: "wallarm/ingress-python:{{ .Values.controller.image.tag }}"
{{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/wallarm
            name: wallarm
          resources:
{{ toYaml (index .Values "controller" "wallarm" "wallarm-appstructure" "resources") | indent 12 }}
        - name: wallarm-antibot
{{- if (index .Values "controller" "wallarm" "wallarm-antibot" "image") }}
  {{- with (index .Values "controller" "wallarm" "wallarm-antibot" "image") }}
          image: "{{ .repository }}:{{ .tag }}"
  {{- end }}
{{- else }}
          image: "wallarm/ingress-python:{{ .Values.controller.image.tag }}"
{{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          command: ["/opt/wallarm/python/usr/bin/antibotapiextractor"]
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/wallarm
            name: wallarm
          resources:
{{ toYaml (index .Values "controller" "wallarm" "wallarm-antibot" "resources") | indent 12 }}
    {{- if .Values.controller.wallarm.tarantool.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.controller.wallarm.tarantool.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.tolerations }}
      tolerations:
{{ toYaml .Values.controller.wallarm.tarantool.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.affinity }}
      affinity:
{{ toYaml .Values.controller.wallarm.tarantool.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.controller.wallarm.tarantool.topologySpreadConstraints | nindent 8 }}
    {{- end }}
      volumes:
        - name: wallarm
          emptyDir: {}
        - name: wallarm-acl
          emptyDir: {}
        - name: wallarm-cron
          configMap:
            name: {{ template "ingress-nginx.wallarmTarantoolCronConfig" . }}
{{- end }}
{{- end }}
