{{- if .Values.controller.wallarm.enabled }}
{{- if eq .Values.controller.wallarm.tarantool.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}-wallarm-tarantool
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.controller.wallarm.tarantool.annotations (and .Values.controller.wallarm.enabled (not .Values.controller.wallarm.existingSecret.enabled)) }}
  annotations:
  {{- if and .Values.controller.wallarm.enabled (not .Values.controller.wallarm.existingSecret.enabled) }}
    checksum/token: {{ .Values.controller.wallarm.token | sha256sum }}
  {{- end }}
  {{- if .Values.controller.wallarm.tarantool.annotations -}}
  {{ toYaml .Values.controller.wallarm.tarantool.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ingress-nginx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "ingress-nginx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    spec:
    {{- if .Values.controller.wallarm.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.controller.wallarm.imagePullSecrets | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.controller.wallarm.tarantool.terminationGracePeriodSeconds }}
      initContainers:
        {{ include "ingress-nginx.wallarmInitContainer.addNode" . | nindent 8 }}
      containers:
        {{ include "ingress-nginx.wallarmCronContainer" . | nindent 8 }}
        - name: tarantool
        {{- if .Values.controller.wallarm.tarantool.image }}
          {{- with .Values.controller.wallarm.tarantool.image }}
          image: "{{ .repository }}:{{ .tag }}"
          {{- end }}
        {{- else }}
          image: "{{ .Values.controller.wallarm.helpers.image }}:{{ .Values.controller.wallarm.helpers.tag }}"
        {{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          args: ["tarantool"]
          env:
            - name: SLAB_ALLOC_ARENA
              value: "{{ .Values.controller.wallarm.tarantool.arena }}"
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ template "ingress-nginx.wallarmTarantoolPort" . }}
            initialDelaySeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controller.wallarm.tarantool.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.controller.wallarm.tarantool.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.controller.wallarm.tarantool.livenessProbe.failureThreshold }}
          ports:
            - name: tarantool
              containerPort: {{ template "ingress-nginx.wallarmTarantoolPort" . }}
              protocol: TCP
        {{- if .Values.controller.wallarm.tarantool.resources }}
          resources: {{ toYaml .Values.controller.wallarm.tarantool.resources | nindent 12 }}
        {{- end }}
        - name: wallarm-appstructure
        {{- if (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
          {{- with (index .Values "controller" "wallarm" "wallarm-appstructure" "image") }}
          image: "{{ .repository }}:{{ .tag }}"
          {{- end }}
        {{- else }}
          image: "{{ .Values.controller.wallarm.helpers.image }}:{{ .Values.controller.wallarm.helpers.tag }}"
        {{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          args: ["appstructure"]
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/wallarm/etc/wallarm
            name: wallarm
        {{- if index .Values "controller" "wallarm" "wallarm-appstructure" "resources" }}
          resources: {{ toYaml (index .Values "controller" "wallarm" "wallarm-appstructure" "resources") | nindent 12 }}
        {{- end }}
        - name: wallarm-antibot
        {{- if (index .Values "controller" "wallarm" "wallarm-antibot" "image") }}
          {{- with (index .Values "controller" "wallarm" "wallarm-antibot" "image") }}
          image: "{{ .repository }}:{{ .tag }}"
          {{- end }}
        {{- else }}
          image: "{{ .Values.controller.wallarm.helpers.image }}:{{ .Values.controller.wallarm.helpers.tag }}"
        {{- end }}
          imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
          args: ["antibot"]
          securityContext: {{ include "controller.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
          - mountPath: /opt/wallarm/etc/wallarm
            name: wallarm
        {{- if index .Values "controller" "wallarm" "wallarm-antibot" "resources" }}
          resources: {{ toYaml (index .Values "controller" "wallarm" "wallarm-antibot" "resources") | nindent 12 }}
        {{- end }}
    {{- if .Values.controller.wallarm.tarantool.nodeSelector }}
      nodeSelector: {{ toYaml .Values.controller.wallarm.tarantool.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.tolerations }}
      tolerations: {{ toYaml .Values.controller.wallarm.tarantool.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.affinity }}
      affinity: {{ toYaml .Values.controller.wallarm.tarantool.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.wallarm.tarantool.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.controller.wallarm.tarantool.topologySpreadConstraints | nindent 8 }}
    {{- end }}
      volumes:
        - name: wallarm
          emptyDir: {}
        - name: wallarm-acl
          emptyDir: {}
        - name: wallarm-cron
          configMap:
            name: {{ template "ingress-nginx.wallarmTarantoolCronConfig" . }}
        {{- include "ingress-nginx.wallarmTokenVolume" . | nindent 8 }}
{{- end }}
{{- end }}
