apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "ingress-nginx.wallarmTarantoolCronConfig" . }}
  namespace: {{ .Release.Namespace }}
data:
  crontab: |
    {{- with .Values.controller.wallarm.cron.jobs.exportAttacks }}
    # export-attacks
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-attacks -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.exportCounters }}
    # export-counters
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-counters -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.exportEnvironment }}
    # export-environment
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-environment -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.bruteDetect }}
    # brute-detect
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/brute-detect -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.syncMarkers }}
    # sync-markers
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/sync-markers -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.weakJwtDetect }}
    # weak-jwt-detect
    {{ .schedule }} /opt/wallarm/ruby/usr/share/wallarm-common/weak-jwt-detect -l STDOUT
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.syncNode }}
    # sync-node
    {{ .schedule }} /opt/wallarm/ruby/usr/share/wallarm-common/syncnode -f -p -r 120 -l STDOUT -L DEBUG
    {{- end }}

    {{- with .Values.controller.wallarm.cron.jobs.exportBlockedStat }}
    # export-blocked-stats
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-blocked-stats -l STDOUT -L DEBUG
    {{- end }}