options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240718-5ef92b5c36
    env:
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && cd images/test-runner && make push
