timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  # job builds a multi-arch docker image for amd64,arm,arm64 and s390x.
  machineType: E2_HIGHCPU_8
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - SHORT_SHA=$SHORT_SHA
      - BASE_REF=$_PULL_BASE_REF
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
      # default cloudbuild has HOME=/builder/home and docker buildx is in /root/.docker/cli-plugins/docker-buildx
      # set the home to /root explicitly to if using docker buildx
      - HOME=/root
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && cd images/httpbun && make push
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
