controller:
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null

  service:
    type: ClusterIP

  wallarm:
    apiHost: api.wallarm.com
    metrics:
      enabled: true

  kind: Deployment

  opentelemetry:
    enabled: true
