controller:
  kind: DaemonSet
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: true
  service:
    type: ClusterIP
