controller:
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  config:
    use-proxy-protocol: "true"
  allowSnippetAnnotations: false
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
