controller:
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP

tcp:
  9000: "default/test:8080"

udp:
  9001: "default/test:8080"
