controller:
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
  containerSecurityContext:
    allowPrivilegeEscalation: false
  extraModules:
    - name: opentelemetry
      image: busybox
