controller:
  wallarm:
    apiHost: api.wallarm.com
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  autoscaling:
    enabled: true
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
