controller:
  image:
    repository: wallarm/ingress-controller
    tag: 1.0.0-dev
    digest: null
  admissionWebhooks:
    enabled: false
  addHeaders:
    X-Frame-Options: deny
  proxySetHeaders:
    X-Forwarded-Proto: https
  service:
    type: ClusterIP
