name: Publish Helm
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+upstream*'
      - '[0-9]+.[0-9]+.[0-9]+-rc*'

permissions:
  contents: read

jobs:
  release:
    runs-on: self-hosted-amd64-1cpu
    outputs:
      chart_version: ${{ steps.check_release.outputs.tag }}
      release_type: ${{ steps.check_release.outputs.type }}
    steps:
      - name: Import secrets
        uses: hashicorp/vault-action@affa6f04da5c2d55e6e115b7d1b044a6b1af8c74 # v2.7.4
        id: secrets
        with:
          exportEnv: false
          url: ${{ secrets.VAULT_URL }}
          role: ${{ secrets.VAULT_ROLE }}
          method: kubernetes
          path: kubernetes-ci
          secrets: |
            kv-gitlab-ci/data/github/shared/github_token token ;

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Check release type
        id: check_release
        run: |
          TYPE="production"
          TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/[+-].*$//g')
          if [[ ${GITHUB_REF#refs/*/} =~ "rc" ]]; then
            TYPE="release-candidate"
            TAG=${GITHUB_REF#refs/*/}
          fi
          echo -e "Type: ${TYPE} \nTag: ${TAG}"
          echo "type=${TYPE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Publish Helm chart
        if: steps.check_release.outputs.type == 'release-candidate'
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260
        with:
          token: ${{ steps.secrets.outputs.token }}
          charts_dir: ./charts
          charts_url: https://charts.wallarm.com
          linting: off
          repository: helm-charts
          branch: main
          target_dir: wallarm-ingress
          index_dir: .
          chart_version: ${{ steps.check_release.outputs.tag }}
