name: Performance Test
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'K6 Load Test'  

permissions:
  contents: read

jobs:
  k6_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make dev-env
        run: |
          mkdir $HOME/.kube
          make dev-env
          podName=`kubectl -n ingress-nginx get po | grep -i controller | awk '{print $1}'`
          if [[ -z ${podName} ]] ; then 
            sleep 5
          fi
          kubectl wait pod -n ingress-nginx --for condition=Ready $podName --timeout=180s
          kubectl get all -n ingress-nginx

      - name: Deploy workload
        run: |
          kubectl create deploy k6 --image kennethreitz/httpbin --port 80 --replicas 3
          kubectl expose deploy k6 --port 80
          kubectl create ing k6 --class nginx --rule test.ingress-nginx-controller.ga/*=k6:80
          podName=`kubectl get po | grep -i k6 | awk '{print $1}'`
          if [[ -z ${podName} ]] ; then 
            sleep 5
          fi
          kubectl wait pod --for condition=Ready $podName
          kubectl get all,secrets,ing

      - name: Run load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test/k6/loadtest.js
          flags: --insecure-skip-tls-verify