# The workflow aims to run on daily basis from the main branch. Also can be run manually by QA for debugging Node tests for Ingress
name: Smoke_Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag of pytest docker image
        type: string
        default: latest
        required: false
  schedule:
    - cron: '00 7,12 * * 1-5'

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke
    runs-on: self-hosted-amd64-2cpu
    strategy:
      fail-fast: false
      matrix:
        k8s: [ v1.23.13, v1.27.1 ]
    steps:
      - name: Import secrets
        uses: hashicorp/vault-action@9f522b85981b491eab9a52c144d15aedbd0bf371 # v2.8.0
        id: secrets
        with:
          exportEnv: false
          url: ${{ secrets.VAULT_URL }}
          role: ${{ secrets.VAULT_ROLE }}
          method: kubernetes
          path: kubernetes-ci
          secrets: |
            kv-gitlab-ci/data/github/ingress api_token ;
            kv-gitlab-ci/data/github/ingress api_host ;
            kv-gitlab-ci/data/github/ingress api_preset ;
            kv-gitlab-ci/data/github/ingress client_id ;
            kv-gitlab-ci/data/github/ingress user_secret ;
            kv-gitlab-ci/data/github/ingress user_uuid ;
            kv-gitlab-ci/data/github/shared/allure allure_endpoint ;
            kv-gitlab-ci/data/github/shared/allure allure_project_id ;
            kv-gitlab-ci/data/github/shared/allure allure_token ;
            kv-gitlab-ci/data/github/shared/smoke-tests-registry-creds token_name ;
            kv-gitlab-ci/data/github/shared/smoke-tests-registry-creds token_secret ;

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.0.2

      - name: Create cluster
        run: kind create cluster --image=kindest/node:${{ matrix.k8s }}

      - name: Run smoke tests
        env:
          ARCH: amd64
          KIND_CLUSTER_NAME: kind
          SKIP_CLUSTER_CREATION: true
          SKIP_IMAGE_CREATION: true
          SKIP_IMAGE_LOADING: true
          WALLARM_API_TOKEN: ${{ steps.secrets.outputs.api_token }}
          WALLARM_API_HOST: ${{ steps.secrets.outputs.api_host }}
          WALLARM_API_PRESET: ${{ steps.secrets.outputs.api_preset }}
          CLIENT_ID: ${{ steps.secrets.outputs.client_id }}
          USER_UUID: ${{ steps.secrets.outputs.user_uuid }}
          USER_SECRET: ${{ steps.secrets.outputs.user_secret }}
          SMOKE_REGISTRY_TOKEN: ${{ steps.secrets.outputs.token_name }}
          SMOKE_REGISTRY_SECRET: ${{ steps.secrets.outputs.token_secret }}
          ALLURE_UPLOAD_REPORT: true
          ALLURE_GENERATE_REPORT: true
          ALLURE_TOKEN: ${{ steps.secrets.outputs.allure_token }}
          ALLURE_ENDPOINT: ${{ steps.secrets.outputs.allure_endpoint }}
          ALLURE_PROJECT_ID: ${{ steps.secrets.outputs.allure_project_id }}
          ALLURE_ENVIRONMENT_K8S: ${{ matrix.k8s }}
          ALLURE_ENVIRONMENT_ARCH: amd64
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ];
          then
            export SMOKE_IMAGE_TAG="${{ github.event.inputs.tag }}"
          fi
          kind get kubeconfig > $HOME/.kube/kind-config-kind
          export KUBECONFIG=$HOME/.kube/kind-config-kind
          make TAG=$(cat TAG) kind-smoke-test
